{
    'name': 'Pharmacy Management System',
    'version': '1.0',
    'summary': 'Manage pharmacy operations',
    'author': 'By Petra Software Industries',
    'depends': ['base', 'mail', 'report_xlsx', 'base_automation'],
    'data': [
        # 'security/security.xml',
        # 'security/ir.model.access.csv',
        # 'data/demo_data.xml',
        # 'data/sequence.xml',
        # 'data/scheduled_actions.xml',
        # 'views/menu.xml',
        # 'views/prescription_views.xml',
        # 'views/patient_views.xml',
        # 'views/doctor_views.xml',
        # 'report/prescription_report.xml',
        # 'report/prescription_template.xml',
        # 'wizard/export_excel_view.xml',
        # 'wizard/export_excel_template.xml',
    ],
    'installable': True,
    'application': True,
}