{
    'name': 'Pharmacy Management System',
    'version': '1.0',
    'summary': 'Manage pharmacy operations',
    'author': 'By Petra Software Industries',
    'depends': ['base', 'mail', 'report_xlsx', 'base_automation', 'point_of_sale', 'stock' , 'sale_management' , 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/medicine_categories.xml',
        'views/menu.xml',
        'views/medicine_views.xml',
        'views/prescription_views.xml',
        'wizard/export_excel_view.xml',
        # 'views/dashboard_views.xml',
        # 'data/scheduled_actions.xml',
        # 'security/security.xml',
        # 'data/demo_data.xml',
        # 'report/prescription_report.xml',
        # 'report/prescription_template.xml',
        # 'wizard/export_excel_template.xml',
    ],
    'installable': True,
    'application': True,
}